language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '16'
  - '14'
  - '12'
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
